# Introduction to Using Python for Quantum Mechanics Problems

Python is a powerful and flexible programming language that can be used to solve many kinds of scientific problems. The wide variety of modules and libraries that are available for Python have specific uses for particular kinds of problems. In this notebook, you will learn to use the `numpy` module and the asociated `linalg` library to do common linear algebra manipulations that readily appear in quantum mechanics problems. In so doing, you will solve homework problems 1 and 2 again, but this time using Python. The idea is that while these homework problems are analytically tractable and not terrible cumbersome, other problems you might encounter will not be and using something like `numpy.linalg` will be very useful.

## Introduction

We begin by importing `numpy` and the linear algebra library (`linalg`) that will make certain calculations easier. The design of this notebook is such that you are shown how to do a certain kind of calculation and then must do the same kind of calculation for the problem you are working.

In [1]:
import numpy as np
import numpy.linalg as la

### Create vectors and take their dot product

The `numpy` module allows us to create numpy arrays which can be maniuplated like vectors and matrices. As you know there's two kinds of vectors, row and column vectors. Making each of these requires a slightly different syntax as you see below.

In [16]:
## Create a row and column vector
rowVec = np.array([[2,3]])
colVec = np.array([[4],[5]])

## Print row vector and shape
print('rowVec:\n', rowVec)
print('rowVec shape:\n', rowVec.shape)

## Print column vector and shape
print('colVec:\n', colVec)
print('colVec shape:\n', colVec.shape)

rowVec:
 [[2 3]]
rowVec shape:
 (1, 2)
colVec:
 [[4]
 [5]]
colVec shape:
 (2, 1)


We can take the dot product of these two vectors by using `np.vdot()` and passing the two vectors to the method. [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html#numpy.vdot).

In [29]:
print(np.vdot(rowVec,colVec))

23


This operation can also be down with the `@` operator and will produce the same result as an array.

In [30]:
rowVec @ colVec

array([[23]])

One useful method for numpy arrays is the "transpose" method which swaps rows and columns creating the transpose of the vector (or matrix). It can be called quite simply using '.T'. As you will see, this method is very useful when computing expectation values and probabilities.

In [23]:
## Print row vector and shape
print('rowVec:\n', rowVec)
print('rowVec shape:\n', rowVec.shape)

## Print transpose of row vector and shape
print('rowVec.T:\n',rowVec.T)
print('rowVec.T shape:\n', rowVec.T.shape)

rowVec:
 [[2 3]]
rowVec shape:
 (1, 2)
rowVec.T:
 [[2]
 [3]]
rowVec.T shape:
 (2, 1)


### Create state vectors and show orthonormality

<font size=8 color="#009600">&#9998;</font> Do This.

* Create two numpy arrays that represent the spin up and spin down vectors in the $S_z$ basis. Recall that we typically use column vectors for this representation. 
* Compute the approrpiate dot products to demonstrate that this basis is orthonormal.

In [ ]:
## Your code here