# Introduction to Using Python for Quantum Mechanics Problems

Python is a powerful and flexible programming language that can be used to solve many kinds of scientific problems. The wide variety of modules and libraries that are available for Python have specific uses for particular kinds of problems. In this notebook, you will learn to use the `numpy` module and the asociated `linalg` library to do common linear algebra manipulations that readily appear in quantum mechanics problems. In so doing, you will solve homework problems 1 and 2 again, but this time using Python. The idea is that while these homework problems are analytically tractable and not terrible cumbersome, other problems you might encounter will not be and using something like `numpy.linalg` will be very useful.

# Introduction

We begin by importing `numpy` and the linear algebra library (`linalg`) that will make certain calculations easier. The design of this notebook is such that you are shown how to do a certain kind of calculation and then must do the same kind of calculation for the problem you are working.

In [1]:
import numpy as np
import numpy.linalg as la
import math

## Create vectors and take their dot product

The `numpy` module allows us to create numpy arrays which can be maniuplated like vectors and matrices. As you know there's two kinds of vectors, row and column vectors. Making each of these requires a slightly different syntax as you see below.

In [2]:
## Create a row and column vector
rowVec = np.array([[2,3]])
colVec = np.array([[4],[5]])

## Print row vector and shape
print('rowVec:\n', rowVec)
print('rowVec shape:\n', rowVec.shape)

## Print column vector and shape
print('colVec:\n', colVec)
print('colVec shape:\n', colVec.shape)

rowVec:
 [[2 3]]
rowVec shape:
 (1, 2)
colVec:
 [[4]
 [5]]
colVec shape:
 (2, 1)


We can take the dot product of these two vectors by using `np.vdot()` and passing the two vectors to the method. [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html#numpy.vdot).

In [3]:
print(np.vdot(rowVec,colVec))

23


This operation can also be down with the `@` operator and will produce the same result as an array.

In [4]:
rowVec @ colVec

array([[23]])

One useful method for numpy arrays is the "transpose" method which swaps rows and columns creating the transpose of the vector (or matrix). It can be called quite simply using '.T'. As you will see, this method is very useful when computing expectation values and probabilities.

In [5]:
## Print row vector and shape
print('rowVec:\n', rowVec)
print('rowVec shape:\n', rowVec.shape)

## Print transpose of row vector and shape
print('rowVec.T:\n',rowVec.T)
print('rowVec.T shape:\n', rowVec.T.shape)

rowVec:
 [[2 3]]
rowVec shape:
 (1, 2)
rowVec.T:
 [[2]
 [3]]
rowVec.T shape:
 (2, 1)


## Create state vectors and show orthonormality

<font size=8 color="#009600">&#9998;</font> Do This.

* Create two numpy arrays that represent the spin up and spin down vectors in the $S_z$ basis. Recall that we typically use column vectors for this representation. 
* Compute the approrpiate dot products to demonstrate that this basis is orthonormal.

In [6]:
## Your code here

# Create matrices and perform matrix multiplication

We can also have `numpy` create matrices and perform matrix multiplication. For example, if we wanted to compute the product of a 2 by 2 martix and a 2 by 1 vector, we would need to first create both arrays and then multiply them with the `@` operator.

$$\vec{b} = \mathbf{M}\:\vec{a}$$

Let's see how that works with `numpy`.

In [8]:
## Create a 2 by 1 column vector
a = np.array([[2],[1]])
print('a:\n', a)

## Create a 2 by 2 matrix
M = np.array([[4,3],[0,1]])
print('M:\n', M)

a:
 [[2]
 [1]]
M:
 [[4 3]
 [0 1]]


In [9]:
## Multiply M and a to make a new 2 by 1 vector b

b = M @ a
print('b:\n', b)

b:
 [[11]
 [ 1]]


## Create a spin matrix and investigate eigenstates

<font size=8 color="#009600">&#9998;</font> Do This.

Earlier you created two vectors that represent the spin up and down state vectors in the $S_z$ basis. These vectors are eigenstates of the $S_z$ operator, which means if the $S_z$ operator is used on them, then you should get the state vector back along multiplied by its eigenvalue. The $S_z$ operator as a matrix is given by:

$$S_z \doteq \dfrac{\hbar}{2}\begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}$$

The $\hbar$ doesn't play nicely with Python, so we will instead use the operator scaled by $\hbar$,

$$\dfrac{S_z}{\hbar} \doteq \dfrac{1}{2}\begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}$$

* Create this operator
* Multiply this operator times the eigenstates to show that you return $\dfrac{1}{2}|+\rangle$ and $\dfrac{-1}{2}|-\rangle$. *We can always multiply our answer by $\hbar$ to get the units right later.*

In [10]:
### your code here

# Complex numbers with Python

Everything we have done so far has used real numbers, but one of the major parts of quantum mechanics is the use of complex numbers in both state vectors and operators. So we will need to represent complex numbers in Python and now how to manipulate them.

Complex numbers are constructed using `j` or `complex()` and can be used in numpy arrays quite easily. Let's construct the number

$$z = 1 + 2i$$

and find it's real part, imaginary part, magnitude, phase, and complex conmjugate. These are all common operations with complex numbers that we will also use in quantum mechanics.

In [12]:
## Create z; notice there's no space or operator between 2 and j
z = 1 + 2j 
print('z:', z)

## Similarly we can use complex() - this is often more useful
z2 = np.complex(1,2)
print('z2:', z2)

z: (1+2j)
z2: (1+2j)


In [13]:
## Real part of z
print('Re(z):', z.real)

## Imaginary part of z
print('Im(z):', z.imag)

## Magnitude of z
print('|z|:', np.abs(z))

## Phase of z
print('Phi (rads):', math.atan2(z.imag, z.real))
print('Phi (degs):', math.atan2(z.imag, z.real)/math.pi*180)

## Complex conjugate of z
print('z*:', np.conj(z))

Re(z): 1.0
Im(z): 2.0
|z|: 2.23606797749979
Phi (rads): 1.1071487177940904
Phi (degs): 63.43494882292201
z*: (1-2j)


## Create spin matrices
<font size=8 color="#009600">&#9998;</font> Do This.

Now, that you have seen how we can create imaginary numbers we are ready to continue with some quantum mechanics calculations. Using what you have learned about matrices and complex numbers in Python:

* Create the $S_x$ and $S_y$ operators. Remember you can divide out $\hbar$.

$$\dfrac{S_x}{\hbar} \doteq \dfrac{1}{2}\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$$

$$\dfrac{S_y}{\hbar} \doteq \dfrac{1}{2}\begin{bmatrix} 0 & -i \\ i & 0 \end{bmatrix}$$

In [14]:
## your code here

## Compute expectation values

<font size=8 color="#009600">&#9998;</font> Do This.

Now that you have represented $S_x$, $S_y$, and $S_z$, we can compute the expectation values for our spin up and down state vectors. These are not terribly exciting, but they will help us with the process. Remember, we are trying to compute:

$$\langle S_z \rangle = \langle \psi | S_z | \psi \rangle$$

So we will need to compute the complex conjugate transpose for $\langle \psi |$ before peforming our calculation. 
* Take $\langle S_z \rangle$ for the spin up vector as the example (we should get 0.5 because it is an eigenstate of $S_z$) and compute $\langle S_x \rangle$ and $\langle S_y \rangle$ yourself. 
* What do expect to get for $\langle S_x \rangle$ and $\langle S_y \rangle$ for an eigenstate of $S_z$?

In [16]:
SZ = 0.5*np.array([[1,0],[0,-1]])
spinUp = np.array([[1],[0]])

print('expectation value:\n', np.conj(spinUp.T) @ SZ @ spinUp)

expectation value:
 [[0.5]]


In [17]:
## your code here

# Working with a superpositon state

Now that you have worked with most of the linear algebra operations that you need for time-independent operations on spin angular momentum states, let's work with a superposition state. Consider a particle in a state constructed in the $S_z$ basis:

$$|\psi\rangle = \dfrac{1}{\sqrt{8}}|+\rangle + i\sqrt{\frac{7}{8}}|-\rangle$$

<font size=8 color="#009600">&#9998;</font> Do This.
* Construct this state vector using a linear algebra representation. Hint: Use``complex()``.
* Show that this state vector is normalized. If it isn't, normalize it.
* Compute the probability of observing the particle in the $S_z$ spin up and down states. In which state is the particle more likely to be observed? How does that make sense with the coefficients for the state?

In [19]:
### your code here

## Computing Expectation Values

<font size=8 color="#009600">&#9998;</font> Do This.
* Compute expectation value for $S_z$. How does the sign of this expectation value make sense to you?
* Compute expectation value for $S_x$ and $S_y$. Are you able to say anything about the probabilities of observing the particle in $S_x$ and $S_y$ spin states?

*It's ok to use $\dfrac{S_i}{\hbar}$ as we have done before.*

In [21]:
### your code here

## Computing probabilities of observations

Now that you have computed the expectation values for $S_x$ and $S_y$, let's check the results against the probabilities of finding the particle in eigenstates of those operators. That is, we want to compute things like:

$$P_{+x} = |_x\langle + | \psi \rangle|^2$$

Remember that:
$$|+\rangle_x = \dfrac{1}{\sqrt{2}}\left(|+\rangle + |-\rangle\right)$$
$$|-\rangle_x = \dfrac{1}{\sqrt{2}}\left(|+\rangle - |-\rangle\right)$$
$$|+\rangle_y = \dfrac{1}{\sqrt{2}}\left(|+\rangle + i|-\rangle\right)$$
$$|-\rangle_y = \dfrac{1}{\sqrt{2}}\left(|+\rangle - i|-\rangle\right)$$

<font size=8 color="#009600">&#9998;</font> Do This.
* Compute the probability of finding the particle in each of the above eigenstates.
* How do your results fit with the expectation values you computed in 4.2?

In [23]:
## your code here