# Solving the Eigenvalue Problem in Quantum Mechanics

We begin by importing `numpy` and the linear algebra library (`linalg`) that will make certain calculations easier. The design of this notebook is such that you are shown how to do a certain kind of calculation and then must do the same kind of calculation for the problem you are working.

In [1]:
import numpy as np
import numpy.linalg as la
import math

## 1. Finding Eigenvalues and Eigenvectors of Spin Operators

To get started, we will simply familiarize ourselves with what `linalg` can do with matrices that we have used many times. In this section, you will learn how to:
* compute the complex conjugate of a matrix
* compute the adjoint of a matrix (complex conjugate transpose)
* check is a matrix is Hermitian
* find the eigenvalues and eigenvectors of a matrix

Our example matrix is the $S_z$ operator:

$$S_z \doteq \dfrac{\hbar}{2}\begin{bmatrix} 1 & 0 \cr 0 & -1 \end{bmatrix}$$

Because `linalg` doesn't play nice with symbols, we will compute everything in units of $\hbar/2$:

$$\dfrac{2}{\hbar}S_z \doteq \begin{bmatrix} 1 & 0 \cr 0 & -1 \end{bmatrix}$$


### 1.1 Investigating if a matrix is Hermitian
We start by creating the matrix:

In [2]:
S_z = np.array([[1,0],
                [0,-1]])
print(S_z)

[[ 1  0]
 [ 0 -1]]


We can determine the complex conjugate ($S_z^*$) of the by using the `.conj()` method (i.e, `S_z.conj()`). What is nice is that computing the adjoint is then simply using the transpose attribute `.T` on the complex conjugate (i.e., ` S_z.conj().T`) to find the adjoint ($S_z^{\dagger}$). Notice that nothing changes because the $S_z$ operator is real and diagonal, so that $S_z = S_z^{*} = S_z^{\dagger}$.

In [3]:
print('complex conjugate of S_z:\n', S_z.conj())
print('complex conjugate, transpose of S_z:\n', S_z.conj().T)

complex conjugate of S_z:
 [[ 1  0]
 [ 0 -1]]
complex conjugate, transpose of S_z:
 [[ 1  0]
 [ 0 -1]]


We can use these operations to check if the matrix is Hermitian. That is, if $S_z = S_z^{\dagger}$. While this operation is clearly true for $S_z$, if you construct a matrix, you need to know that it is Hermitian because then it's eigenvalues are guaranteed to be real and, thus, it can represent some observaable. We can do this by computing:

$$S_z - S_z^{\dagger}$$

which we expect to be the zero matrix.

In [4]:
print(S_z-S_z.conj().T)

[[0 0]
 [0 0]]


### 1.2 Using `.eig()` to find eigenvalues and eigenvectors

The `linalg` library includes a method (`.eig()`) that will determine the eigenvalues and eigenvectors of a matrix that it is passed. A few things:

1. It returns two variables: the first is a 1D array of the eigenvalues, and the second is 2D array of the eigenvectors.
2. It will work with complex numbers (as we will see)
3. It determines these eigenvalues and eigenvectors numerically, so they can be approximate.
    * Regarding this last point, sometimes an eigenvalue or a component of an eigenvector will be zero, but `.eig()` will return a very small number (i.e., something*$10^{-16}$). This is machine precision (i.e., as close as the computer can get to numerically zero given the data type for the number).
    
We can call `eig()` from the `linalg` library and store the eigenvalues and eigenvectors:

In [5]:
S_z_eigs, S_z_vecs = la.eig(S_z)

As expected, we obtain two real eigenvalues: +1 and -1 (in units of $\hbar/2$). We can store and print them.

In [6]:
lambda0, lambda1 = S_z_eigs[0], S_z_eigs[1]
print('lambda0:\n',lambda0)
print('lambda1:\n',lambda1)

lambda0:
 1.0
lambda1:
 -1.0


We also obtain two eigenvectors that have two components. One of the curious things about `.eig()` method is that the columns (NOT THE ROWS) of the matrix that are returned correspond to the eigenvectors. This is not as obvious for this example, but it becomes obvious for other matrices. So we need to store those columns and reshape them to use them for calculations.

In [7]:
v0, v1 = S_z_vecs[:,0].reshape(2,1), S_z_vecs[:,1].reshape(2,1)
print('v0:\n', v0)
print('v1:\n', v1)

v0:
 [[1.]
 [0.]]
v1:
 [[0.]
 [1.]]


### 1.3 Investigating $S_y$

In the example above, we focused on $S_z$ to illustrate the process for determining the eigenvalues and eigenvectors. You will repeat this process for $S_y$ where the matrix is now complex.

$$S_y \doteq \dfrac{\hbar}{2} \begin{bmatrix}0 & -i \cr i & 0 \end{bmatrix}$$

Or in units of $\hbar/2$,

$$\dfrac{2}{\hbar} S_y \doteq \begin{bmatrix}0 & -i \cr i & 0 \end{bmatrix}$$

Recall we can construct complex numbers using `j`. Below we have constructed the $S_y$ matrix in units of $\hbar/2$.

In [8]:
S_y = np.array([[0,-1j],
                [1j,0]])
print(S_y)

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]


#### Check that $S_y$ is Hermitian

<font size=8 color="#009600">&#9998;</font> Do This.

* Compute $S_y^*$ and $S_y^{\dagger}$.
* Show that $S_y$ is Hermitian.

In [9]:
## your code here

#### Determine the eigenvalues and eigenvectors of $S_y$

<font size=8 color="#009600">&#9998;</font> Do This.

* Determine the eigenvalues of $S_y$. What do you notice about them? What does Python produce (a real or complex number)?
    * Do you expect the eigenvalue to be real or not? If it is meant to be real, how can you force Python to print (or store) the real part only?
* Determine the eigenvectors. How do these compare to what you have seen before?

In [11]:
## your code here

## 2. Automate the process

Now that you have worked with the `linalg` library a bit, you will write a function (`ComputeEig`) that will take a Hermitian matrix and return its eigenvalues and eigenvectors. In doing this, you will need to check that the matrix that is passed is both square and Hermitian before it performs operations. The function should return the real eigenvalues and the eigenvectors if the matrix is both square and Hermitian. If either is not true, the function should through an error and indicate the problem.

All that `ComputeEig` should take as a variable is the matrix you intend to use.

`def ComputeEig(M):`

We have given you some test matrices to check your function.

In [13]:
### your code here

### 2.1 Test case 1

Should fail as it is not square.

$a = \begin{bmatrix} 1 \cr 1 \end{bmatrix}$

In [15]:
a = np.array([[1],[1]])
print('a:\n', a)
## ComputeEig(a)

a:
 [[1]
 [1]]


### 2.2 Test case 2

Should pass as it is Hermitian. We also should expect $\lambda$'s equal to 1, 3/2, and 5/2.

$H = \begin{bmatrix} 2 & 0 & 0.5 \cr 0 & 1 & 0 \cr 0.5 & 0 & 2 \end{bmatrix}$

In [16]:
H = np.array([[2,0,0.5],
              [0,1,0],
              [0.5,0,2]])
print('H:\n', H)
##ComputeEig(H)

H:
 [[2.  0.  0.5]
 [0.  1.  0. ]
 [0.5 0.  2. ]]


### 2.3 Test case 3

Should fail as it is not Hermitian.

$T = \begin{bmatrix} 2 & 1 & 10 \cr 0 & 1 & 1 \cr 0 & 0 & 2 \end{bmatrix}$

In [17]:
T = np.array([[2,1,10],
              [0,1,1],
              [0,0,2]])
print('T:\n', T)
## ComputeEig(T)

T:
 [[ 2  1 10]
 [ 0  1  1]
 [ 0  0  2]]


### 2.4 Test case 4

Should pass as it is Hermitian. We also should expect $\lambda$'s equal to 1, 3/2, and 5/2.

$C = \begin{bmatrix} 2 & 0 & 0.5i \cr 0 & 1 & 0 \cr -0.5i & 0 & 2 \end{bmatrix}$

In [18]:
C = np.array([[2,0,0.5j],
              [0,1,0],
              [-0.5j,0,2]]) 

print('C:\n', C)
## ComputeEig(C)

C:
 [[ 2.+0.j   0.+0.j   0.+0.5j]
 [ 0.+0.j   1.+0.j   0.+0.j ]
 [-0.-0.5j  0.+0.j   2.+0.j ]]


### 2.5 Create your own 4 by 4 matrix

<font size=8 color="#009600">&#9998;</font> Do This.

* Create a 4 by 4 Hermitian matrix. It should have complex values.
* Run `ComputeEig` on your matrix and determine its eigenvalues and eigenvectors

In [19]:
## your code here